apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cold
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual 
  hostPath:
    path: /mnt/data/clickhouse/data-cold/
    type: DirectoryOrCreate  
