# PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hot
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  
  hostPath:
    path: /mnt/data/clickhouse/data-hot/
    type: DirectoryOrCreate   
