---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cold
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  
