apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-userconfigmap
  namespace: clickhouse
data:
  storage.xml: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
      <path>/data/clickhouse/</path>  <!-- Hot data path on local storage -->

      <disks>
        <!-- Default local disk for hot storage -->
        <default>
          <path>/data/clickhouse/</path> <!-- Hot data stored locally -->
        </default>

        <!-- S3 disk for cold storage -->
        <s3>
          <type>s3</type>
          <endpoint>https://s3-bucket-clickhouse-1.s3.us-east-1.amazonaws.com/data/</endpoint> <!-- Replace with your S3 bucket endpoint -->
          #<access_key_id>AKIA5FTZCHRINFSSSCXM</access_key_id> <!-- Your AWS Access Key -->
          #<secret_access_key>loHd78xdP7nKyZ92y8qLuNQLRx1HbAYwq2FPrAbg</secret_access_key> <!-- Your AWS Secret Key -->
          <region>us-east-1</region> <!-- S3 region -->
          <use_environment_credentials>false</use_environment_credentials>
          <metadata_path>/var/lib/clickhouse/disks/s3/</metadata_path> <!-- Path for storing metadata locally -->
        </s3>

        <!-- S3 cache for cold data -->
        <s3_cache>
          <type>cache</type>
          <disk>s3</disk>
          <path>/var/lib/clickhouse/disks/s3_cache/</path> <!-- Cache path -->
          <max_size>10Gi</max_size> <!-- Maximum cache size -->
        </s3_cache>
      </disks>

      <policies>
        <!-- Cold storage policy using S3 -->
        <s3_main>
          <volumes>
            <main>
              <disk>s3</disk> <!-- Cold storage will use S3 -->
            </main>
          </volumes>
        </s3_main>

        <!-- Tiered storage policy: Hot data on local disk, cold data on S3 -->
        <s3_tiered>
          <volumes>
            <hot>
              <disk>default</disk> <!-- Hot data will be stored on local disk -->
            </hot>
            <main>
              <disk>s3</disk> <!-- Cold data will be stored on S3 -->
            </main>
          </volumes>
          <move_factor>0.2</move_factor> <!-- Move data to cold storage when disk usage exceeds 20% -->
        </s3_tiered>
      </policies>
    </clickhouse>

  access_management.xml: |
    <clickhouse>
      <users>
        <default>
          <access_management>1</access_management>
          <named_collection_control>1</named_collection_control>
          <show_named_collections>1</show_named_collections>
          <show_named_collections_secrets>1</show_named_collections_secrets>
          <double_sha1_passwords>1</double_sha1_passwords>
        </default>
      </users>
    </clickhouse>

  users.xml: |
    <?xml version="1.0"?>
    <clickhouse>
      <profiles>
        <!-- Default profile with memory and load balancing configurations -->
        <default>
          <max_memory_usage>10000000</max_memory_usage> <!-- Set max memory usage to 10 GB -->
          <load_balancing>random</load_balancing>
        </default>
        <!-- Readonly profile with readonly flag set -->
        <readonly>
          <readonly>1</readonly>
        </readonly>
      </profiles>

      <users>
        <!-- Default user configuration -->
        <default>
          <password_double_sha1_hex>7dc366355ed7a983876a29d69a9586d5c2bd98b4</password_double_sha1_hex>
          <networks>
            <ip>::/0</ip> <!-- Allow connections from any IP address -->
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </default>
      </users>

      <quotas>
        <default>
          <interval>
            <duration>3600</duration> <!-- 1 hour interval -->
            <queries>1000</queries> <!-- Allow 1000 queries per interval -->
            <errors>20</errors> <!-- Allow 20 errors per interval -->
            <result_rows>10000000</result_rows> <!-- Limit to 10 million result rows -->
            <read_rows>100000000</read_rows> <!-- Limit to 100 million read rows -->
            <execution_time>3600</execution_time> <!-- Max execution time of 3600 seconds (1 hour) -->
          </interval>
        </default>
      </quotas>
    </clickhouse>