apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: s3.csi.aws.com
    volumeHandle: "s3-bucket-clickhouse" # Replace with your bucket name
    nodePublishSecretRef:
      name: s3-secret # Secret for bucket credentials
      namespace: clickhouse