apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: clickhouse-s3
