apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
type: Opaque
stringData:
  accessKeyID: "AKIAXYKJTM6X3ECREOP6"
  secretAccessKey: "uoDskLhtYUaG2peabS+EsIfv2GgR38Sxl6UotxT6"
  region: "us-east-1" # e.g., us-east-1
