apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  type: NodePort # Change to LoadBalancer or NodePort if external access is required
  ports:
    - name: http
      protocol: TCP
      port: 80          # Exposed port
      targetPort: 8123  # Maps to the ClickHouse HTTP interface
    - name: native
      protocol: TCP
      port: 9000        # Exposed port
      targetPort: 9000  # Maps to the ClickHouse native interface