apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  
  hostPath:
    path: /mnt/data/clickhouse  
    type: DirectoryOrCreate  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: manual

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-userconfigmap
  namespace: clickhouse
data:
  storage.xml: |
    <clickhouse>
        <listen_host>0.0.0.0</listen_host>
        <path>/data/clickhouse/</path>
        <user_directories>
            <local_directory>
                <path>/data/</path>
            </local_directory>
        </user_directories>
    </clickhouse>

  access_management.xml: | 
    <clickhouse>
      <users>
        <default>
          <access_management>1</access_management>
          <named_collection_control>1</named_collection_control>
          <show_named_collections>1</show_named_collections>
          <show_named_collections_secrets>1</show_named_collections_secrets>
          <double_sha1_passwords>1</double_sha1_passwords>
        </default>
      </users>
    </clickhouse>

  users.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <profiles>
            
            <default>
                <max_memory_usage>10000000</max_memory_usage>  
                <load_balancing>random</load_balancing>
            </default>
     
            <readonly>
                <readonly>1</readonly>
            </readonly>
        </profiles>

        <users> 
          <default>
            <profile>default</profile>
            <password>admin</password>
            <quota>default</quota>
            <networks>
              <ip>::/0</ip>
            </networks>
          </default>
        </users>

        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>  
                    <queries>1000</queries>  
                    <errors>20</errors>  
                    <result_rows>10000000</result_rows>  
                    <read_rows>100000000</read_rows>  
                    <execution_time>3600</execution_time>  
                </interval>
            </default>
        </quotas>
    </clickhouse>




 
---

apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  selector:
    app: clickhouse
  type: NodePort # Change to LoadBalancer or NodePort if external access is required
  ports:
    - name: http
      protocol: TCP
      port: 8123          # Exposed port
      targetPort: 8123  # Maps to the ClickHouse HTTP interface
    - name: native
      protocol: TCP
      port: 9000        # Exposed port
      targetPort: 9000  # Maps to the ClickHouse native interface


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      volumes:
        - name: clickhouse-userconfigmap
          configMap:
            name: clickhouse-userconfigmap
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.8.8.17
          ports:
            - containerPort: 8123
            - containerPort: 9000
          resources:
            limits:
              cpu: 600m
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 1Gi
          volumeMounts:
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/users.xml
              subPath: users.xml
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/users.d/default.xml
              subPath: access_management.xml
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/config.d/default_config.xml
              subPath: storage.xml
            - name: clickhouse-storage
              mountPath: /data