apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: manual  # Same as PersistentVolume's storageClassName 
